//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStreamingSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.StudentResults = new HashSet<StudentResult>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public System.DateTime CourseCreatedDate { get; set; }
        public string CrHrs { get; set; }
        public string CourseCode { get; set; }
        public string ClassType { get; set; }
        public string ThemeColor { get; set; }
        public Nullable<System.DateTime> BeginsAt { get; set; }
        public Nullable<System.DateTime> EndsAt { get; set; }
        public string CourseType { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> No_Of_Seats { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> PrerequisiteID { get; set; }
        public string TestName { get; set; }
        public string TestTermName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentResult> StudentResults { get; set; }
    }
}
