//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStreamingSystem.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentStreamingDBEntities : DbContext
    {
        public StudentStreamingDBEntities()
            : base("name=StudentStreamingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicStudentResult> AcademicStudentResults { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Prerequisite> Prerequisites { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
        public virtual DbSet<Course_has_PreRequisite> Course_has_PreRequisite { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<StudentResult> StudentResults { get; set; }
        public virtual DbSet<StudentCourseSelection> StudentCourseSelections { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
    
        public virtual int get_SelectedCourse(Nullable<int> courseId)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_SelectedCourse", courseIdParameter);
        }
    }
}
